### PR TITLE
Polish translation

### PR DESCRIPTION
**Pull request by Warenhari**

### CODE REVIEW

**Comment by Warenhari** [comment]
I wasn't sure about `"Promotional": "Promocyjne"`. Depending on the usage, it may be something different. I haven't found where it is used in app.

**Comment by neizerth** [comment]
Thank you very much!

> I wasn't sure about `"Promotional": "Promocja"`. Depending on the usage, it may be something different. I haven't found where it is used in app.

If you click at the "Investigators" tab, this is the last item in the Select Campaign dropdown :)

**Comment by neizerth** [comment]
image

Here it is

This is promo data from books :)

**Comment by neizerth** [comment]
@Warenhari Is the translation correct for this context?

**Comment by Warenhari** [comment]
Fixed to more descriptive translation.

**Comment by neizerth** [comment]
Great! Thank you!

**Pull request merged**
